stages:
  data_ingestion:
    cmd: python src/Waste_Recycling_Classifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Waste_Recycling_Classifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - datafacts/data_ingestion/Waste Recycling Classification Dataset


  prepare_base_model:
    cmd: python src/Waste_Recycling_Classifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/Waste_Recycling_Classifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - datafacts/prepare_base_model



  training:
    cmd: python src/Waste_Recycling_Classifier/pipeline/stage_03_training.py
    deps:
      - src/Waste_Recycling_Classifier/pipeline/stage_03_training.py
      - src/Waste_Recycling_Classifier/components/prepare_call_backs.py
      - config/config.yaml
      - datafacts/data_ingestion/Waste Recycling Classification Dataset
      - datafacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - datafacts/training/model.h5

  evaluation:
    cmd: python src/Waste_Recycling_Classifier/pipeline/stage_04_evaluation.py
    deps:
      - src/Waste_Recycling_Classifier/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - datafacts/data_ingestion/Waste Recycling Classification Dataset
      - datafacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: false