from Waste_Recycling_Classifier import logger
from Waste_Recycling_Classifier.pipeline.stage_01_data_ingestion import DataIngestionTrainingPipeline
from Waste_Recycling_Classifier.pipeline.stage_02_prepare_base_model import PrepareBaseModelTrainingPipeline
from Waste_Recycling_Classifier.pipeline.stage_03_training import ModelTrainingPipeline
from Waste_Recycling_Classifier.pipeline.stage_04_evaluation import EvaluationPipeline











